import dotenv from "dotenv";
dotenv.config();
import express from "express";
import cors from "cors";
import { PORT } from "./config";
import { userRouter } from "./routes/users";
import { contentRouter } from "./routes/content";
const app = express();
app.use(express.json());
app.use(cors());
app.use("/api/v1/user", userRouter);
app.use("/api/v1/content", contentRouter);
app.listen(PORT);
